
project_id = "gpzoytysrrormkmytmyk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = true

[vector]
enabled = true

[edge_functions]
[edge_functions.mathhub-ai]
verify_jwt = true

[edge_functions.gemini-math-ai]
verify_jwt = true
