
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpzoytysrrormkmytmyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwem95dHlzcnJvcm1rbXl0bXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTU0NTgsImV4cCI6MjA1OTUzMTQ1OH0.8H6jkUG_HkwqZfx6PlQIw9VTetifpYv7OYRJ2KM9W4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Initialize storage buckets
(async () => {
  try {
    // Check if buckets exist
    const { data: buckets } = await supabase.storage.listBuckets();
    
    const bucketsList = {
      avatars: false,
      exam_papers: false,
      solutions: false
    };
    
    // Check which buckets already exist
    buckets?.forEach(b => {
      if (bucketsList.hasOwnProperty(b.name)) {
        bucketsList[b.name as keyof typeof bucketsList] = true;
      }
    });
    
    // Create avatars bucket if it doesn't exist
    if (!bucketsList.avatars) {
      await supabase.storage.createBucket('avatars', {
        public: true,
        fileSizeLimit: 1024 * 1024 * 2 // 2MB
      });
      console.log('Created avatars bucket');
    }
    
    // Create exam_papers bucket if it doesn't exist
    if (!bucketsList.exam_papers) {
      await supabase.storage.createBucket('exam_papers', {
        public: true,
        fileSizeLimit: 1024 * 1024 * 10 // 10MB
      });
      console.log('Created exam_papers bucket');
    }
    
    // Create solutions bucket if it doesn't exist
    if (!bucketsList.solutions) {
      await supabase.storage.createBucket('solutions', {
        public: true,
        fileSizeLimit: 1024 * 1024 * 10 // 10MB
      });
      console.log('Created solutions bucket');
    }
  } catch (error) {
    console.error('Error initializing storage buckets:', error);
  }
})();
