
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpzoytysrrormkmytmyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwem95dHlzcnJvcm1rbXl0bXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTU0NTgsImV4cCI6MjA1OTUzMTQ1OH0.8H6jkUG_HkwqZfx6PlQIw9VTetifpYv7OYRJ2KM9W4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Initialize storage buckets
(async () => {
  try {
    // Check if avatars bucket exists
    const { data: buckets } = await supabase.storage.listBuckets();
    const avatarsBucketExists = buckets?.some(b => b.name === 'avatars');
    
    // Create avatars bucket if it doesn't exist
    if (!avatarsBucketExists) {
      await supabase.storage.createBucket('avatars', {
        public: true,
        fileSizeLimit: 1024 * 1024 * 2 // 2MB
      });
      console.log('Created avatars bucket');
    }
  } catch (error) {
    console.error('Error initializing storage buckets:', error);
  }
})();
